---
title: 'Open vs. closed innovation: using online network data to measure innovation'
author: "Benjamin Snow and Oliver Bott"
date: "11 November 2014"
output:
  pdf_document:
    fig_caption: yes
    number_sections: yes
  html_document:
    fig_caption: yes
    number_sections: no
bibliography:
- Packages.bib
- Main.bib
---

```{r include=FALSE}
# Set working directory. Change as needed
setwd('C:/Users/a6p/Desktop/Uni 2014/E1161 - Collaborative Research/Final Project/')

# Load packages and create BibTeX file
# Note: must have repmis, rsdmx, httr, dplyr and rjson packages installed
PackagesUsed <- c("ggplot2", "repmis", "rsdmx", "httr", "dplyr", "rjson")

# Load PackagesUsed and create .bib BibTeX file
repmis::LoadandCite(PackagesUsed, file = "Packages.bib", install = FALSE)
```




## Introduction

This research project examines the potential preferability of using collaborative online network data on the city-level as an innovation indicator. By doing so, this work will critically assess current innovation indicators in the hope of offering new alternatives for measuring and understanding innovation. Since various scholars, called for the continuous improvement of innovation measurement [see for example @freeman2009], this work seeks to go beyond the widespread use of patent data to contribute to the refinement of innovation indicators, and the field as a whole.

## Data Gathered

## Justification

**Cities**

Why are we using the cities we are, why did we exclude Einhoven etc.

**Pollution**

Pollution data was obtained as a broad proxy for industrialization

**GDP**

Greenspace, employment as share of national employment, pop, 




Due to the exploratory nature of the study, it is important to be aware of the limitation before examining results, to put them in their proper context, and to keep in mind possible more approximate ways in the future.

## Limitations

The constraints of the data used in this study are numerous, but fall largely within three main categories:

Time:

Too Rough a Proxy:

**Defining Innovation**

**Measuring Innovation**

**Limitations of Patent Data**


# Methodology

To examine open network data against patent data, this study will rely largely on two data sets and use the statistical tool R [@CiteR] for the data analysis.

**API network data**

The first data set is obtained by using the Application Programming Interface (API) data for open networks. To examine open data innovation, data is obtained from the the git repository web-based hosting service GitHub[^GIT]. GitHub is a web-based hosting service used for collaborative research. Its use of source code management makes it a commonly used software development collaboration tool. Since most of the repositories are openly accessible one can use API tools to track the popularity of repositories, measured here by the repository user counts. The R [@CiteR] packages @R-httr, @R-dplyr and @R-rjson allow us to compile data on the user counts and locations associated with different repositories.

For the analysis, first create location vectors for different cities with the `locations` code. Since many GitHub users can be located, we will identify different open innovation clusters, for example Berlin, New York and San Francisco. In addition, we use the `vector()` code to get information on user counts, focusing on repositories with more than 20 or so followers. By combining locations and user counts data by using `data.frame()`, we will be able to construct data sets for different location clusters and user count numbers, where users of highly relevant repositories are located.

**Closed innovation OECD patent data**

For closed innovation we use city-level patent data, taken from the Organization for Economic Co-operation and Development[^OECD]. The R [@CiteR] package [@R-rsdmx] is necessary for obtaining the OECD dataset. Patent Cooperation Treaty (PCT) patent data are used to track internationally patented inventions. For our preliminary sample, we took patent data of 20 cities overall, ranging from six different countries, including their country level patent data, for general comparison over the time period 2000 until 2012. As we are interested in patent data, we work with data indicating the PCT patent applications per 10,000 inhabitants. From the same database, we also use GDP per capita data and environmental data, as other variables which could prove significant in explaining differences in innovation. The OECD data will be in a format that allows us to locate patent activity to individual cities. 



**Statistical Model**

On the type of analysis and question, this study plans to use an ordinary least squares (OLS) model by using `plot` and possibly `rcorr( , type="pearson")` to examine the relationship between patent and open data in a given network cluster. If we happen to find a relationship, this would presumably demonstrate that open data shows the same innovation as patent data, but the 'throughput' of innovation rather than the 'output'. Open data having a relationship to patent data would presumably show innovation as a throughput, since it is measured by people finding those contributing in open data as innovators (followers on github), rather than looking at the specific innovation at completion (patents). One limitation we are facing is that the patent data will not be up to date compared to the network data. Still we believe that a general comparison is possible and could lead to valid results.

[^OECD]: Online accessible on [http://stats.oecd.org].
[^GIT]: Online accessilbe on [https://github.com/].

# References
